services:
  - type: web
    name: backend-projeto-tpe
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_api:asgi --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: ALLOWED_ORIGINS
        value: "https://cep-by-j-morais.vercel.app,http://localhost:3000"
      - key: RPI_DEVICE_TOKEN
        sync: false
